services:
  backend-ktor:
    build:
      context: ./ktor
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_URL: ${DB_URL}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: ./react
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend-ktor
